/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupTwoFactorRouteImport } from './routes/setup-two-factor'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppDesignSystemRouteImport } from './routes/_app/design-system'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AppApprovalsIndexRouteImport } from './routes/_app/approvals/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients/new'
import { Route as AppContentIndexRouteImport } from './routes/_app/content/index'
import { Route as AppDepartmentsIndexRouteImport } from './routes/_app/departments/index'
import { Route as AppDepartmentsDepartmentIdRouteImport } from './routes/_app/departments/$departmentId'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app/notifications/index'
import { Route as AppNotificationsSettingsRouteImport } from './routes/_app/notifications/settings'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppRetainersIndexRouteImport } from './routes/_app/retainers/index'
import { Route as AppRetainersRetainerIdRouteImport } from './routes/_app/retainers/$retainerId'
import { Route as AppRetainersNewRouteImport } from './routes/_app/retainers/new'
import { Route as AppShootsNewRouteImport } from './routes/_app/shoots/new'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks/$taskId'
import { Route as AppTasksBoardRouteImport } from './routes/_app/tasks/board'
import { Route as AppTasksListRouteImport } from './routes/_app/tasks/list'
import { Route as AppTasksNewRouteImport } from './routes/_app/tasks/new'
import { Route as AppTasksWorkloadRouteImport } from './routes/_app/tasks/workload'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team/index'
import { Route as AppTeamUserIdRouteImport } from './routes/_app/team/$userId'
import { Route as AppTeamNewRouteImport } from './routes/_app/team/new'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/_app/templates/$templateId'
import { Route as AppTemplatesNewRouteImport } from './routes/_app/templates/new'
import { Route as AppApprovalsRequestsRequestIdRouteImport } from './routes/_app/approvals/requests/$requestId'
import { Route as AppContentPostsPostIdRouteImport } from './routes/_app/content/posts/$postId'
import { Route as AppShootsShootIdIndexRouteImport } from './routes/_app/shoots/$shootId/index'
import { Route as AppShootsShootIdEditRouteImport } from './routes/_app/shoots/$shootId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTwoFactorRoute = SetupTwoFactorRouteImport.update({
  id: '/setup-two-factor',
  path: '/setup-two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AppRoute,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApprovalsIndexRoute = AppApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContentIndexRoute = AppContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsIndexRoute = AppDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsDepartmentIdRoute =
  AppDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsSettingsRoute =
  AppNotificationsSettingsRouteImport.update({
    id: '/notifications/settings',
    path: '/notifications/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRetainersIndexRoute = AppRetainersIndexRouteImport.update({
  id: '/retainers/',
  path: '/retainers/',
  getParentRoute: () => AppRoute,
} as any)
const AppRetainersRetainerIdRoute = AppRetainersRetainerIdRouteImport.update({
  id: '/retainers/$retainerId',
  path: '/retainers/$retainerId',
  getParentRoute: () => AppRoute,
} as any)
const AppRetainersNewRoute = AppRetainersNewRouteImport.update({
  id: '/retainers/new',
  path: '/retainers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppShootsNewRoute = AppShootsNewRouteImport.update({
  id: '/shoots/new',
  path: '/shoots/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksBoardRoute = AppTasksBoardRouteImport.update({
  id: '/tasks/board',
  path: '/tasks/board',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksListRoute = AppTasksListRouteImport.update({
  id: '/tasks/list',
  path: '/tasks/list',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksNewRoute = AppTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksWorkloadRoute = AppTasksWorkloadRouteImport.update({
  id: '/tasks/workload',
  path: '/tasks/workload',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamUserIdRoute = AppTeamUserIdRouteImport.update({
  id: '/team/$userId',
  path: '/team/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamNewRoute = AppTeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRequestsRequestIdRoute =
  AppApprovalsRequestsRequestIdRouteImport.update({
    id: '/approvals/requests/$requestId',
    path: '/approvals/requests/$requestId',
    getParentRoute: () => AppRoute,
  } as any)
const AppContentPostsPostIdRoute = AppContentPostsPostIdRouteImport.update({
  id: '/content/posts/$postId',
  path: '/content/posts/$postId',
  getParentRoute: () => AppRoute,
} as any)
const AppShootsShootIdIndexRoute = AppShootsShootIdIndexRouteImport.update({
  id: '/shoots/$shootId/',
  path: '/shoots/$shootId/',
  getParentRoute: () => AppRoute,
} as any)
const AppShootsShootIdEditRoute = AppShootsShootIdEditRouteImport.update({
  id: '/shoots/$shootId/edit',
  path: '/shoots/$shootId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/design-system': typeof AppDesignSystemRoute
  '/a/$token': typeof ATokenRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/notifications/settings': typeof AppNotificationsSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/retainers/$retainerId': typeof AppRetainersRetainerIdRoute
  '/retainers/new': typeof AppRetainersNewRoute
  '/shoots/new': typeof AppShootsNewRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/board': typeof AppTasksBoardRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/new': typeof AppTasksNewRoute
  '/tasks/workload': typeof AppTasksWorkloadRoute
  '/team/$userId': typeof AppTeamUserIdRoute
  '/team/new': typeof AppTeamNewRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/approvals/': typeof AppApprovalsIndexRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/content/': typeof AppContentIndexRoute
  '/departments/': typeof AppDepartmentsIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/retainers/': typeof AppRetainersIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/approvals/requests/$requestId': typeof AppApprovalsRequestsRequestIdRoute
  '/content/posts/$postId': typeof AppContentPostsPostIdRoute
  '/shoots/$shootId/edit': typeof AppShootsShootIdEditRoute
  '/shoots/$shootId/': typeof AppShootsShootIdIndexRoute
}
export interface FileRoutesByTo {
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/design-system': typeof AppDesignSystemRoute
  '/a/$token': typeof ATokenRoute
  '/': typeof AppIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/notifications/settings': typeof AppNotificationsSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/retainers/$retainerId': typeof AppRetainersRetainerIdRoute
  '/retainers/new': typeof AppRetainersNewRoute
  '/shoots/new': typeof AppShootsNewRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/board': typeof AppTasksBoardRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/new': typeof AppTasksNewRoute
  '/tasks/workload': typeof AppTasksWorkloadRoute
  '/team/$userId': typeof AppTeamUserIdRoute
  '/team/new': typeof AppTeamNewRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/approvals': typeof AppApprovalsIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/content': typeof AppContentIndexRoute
  '/departments': typeof AppDepartmentsIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/retainers': typeof AppRetainersIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/approvals/requests/$requestId': typeof AppApprovalsRequestsRequestIdRoute
  '/content/posts/$postId': typeof AppContentPostsPostIdRoute
  '/shoots/$shootId/edit': typeof AppShootsShootIdEditRoute
  '/shoots/$shootId': typeof AppShootsShootIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/design-system': typeof AppDesignSystemRoute
  '/a/$token': typeof ATokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/_app/notifications/settings': typeof AppNotificationsSettingsRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/retainers/$retainerId': typeof AppRetainersRetainerIdRoute
  '/_app/retainers/new': typeof AppRetainersNewRoute
  '/_app/shoots/new': typeof AppShootsNewRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/tasks/board': typeof AppTasksBoardRoute
  '/_app/tasks/list': typeof AppTasksListRoute
  '/_app/tasks/new': typeof AppTasksNewRoute
  '/_app/tasks/workload': typeof AppTasksWorkloadRoute
  '/_app/team/$userId': typeof AppTeamUserIdRoute
  '/_app/team/new': typeof AppTeamNewRoute
  '/_app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/_app/templates/new': typeof AppTemplatesNewRoute
  '/_app/approvals/': typeof AppApprovalsIndexRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/content/': typeof AppContentIndexRoute
  '/_app/departments/': typeof AppDepartmentsIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/retainers/': typeof AppRetainersIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/approvals/requests/$requestId': typeof AppApprovalsRequestsRequestIdRoute
  '/_app/content/posts/$postId': typeof AppContentPostsPostIdRoute
  '/_app/shoots/$shootId/edit': typeof AppShootsShootIdEditRoute
  '/_app/shoots/$shootId/': typeof AppShootsShootIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/login'
    | '/setup-two-factor'
    | '/account'
    | '/audit'
    | '/design-system'
    | '/a/$token'
    | '/clients/$clientId'
    | '/clients/new'
    | '/departments/$departmentId'
    | '/notifications/settings'
    | '/projects/$projectId'
    | '/projects/new'
    | '/retainers/$retainerId'
    | '/retainers/new'
    | '/shoots/new'
    | '/tasks/$taskId'
    | '/tasks/board'
    | '/tasks/list'
    | '/tasks/new'
    | '/tasks/workload'
    | '/team/$userId'
    | '/team/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/approvals/'
    | '/calendar/'
    | '/clients/'
    | '/content/'
    | '/departments/'
    | '/notifications/'
    | '/projects/'
    | '/retainers/'
    | '/tasks/'
    | '/team/'
    | '/templates/'
    | '/approvals/requests/$requestId'
    | '/content/posts/$postId'
    | '/shoots/$shootId/edit'
    | '/shoots/$shootId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activate'
    | '/login'
    | '/setup-two-factor'
    | '/account'
    | '/audit'
    | '/design-system'
    | '/a/$token'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/departments/$departmentId'
    | '/notifications/settings'
    | '/projects/$projectId'
    | '/projects/new'
    | '/retainers/$retainerId'
    | '/retainers/new'
    | '/shoots/new'
    | '/tasks/$taskId'
    | '/tasks/board'
    | '/tasks/list'
    | '/tasks/new'
    | '/tasks/workload'
    | '/team/$userId'
    | '/team/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/approvals'
    | '/calendar'
    | '/clients'
    | '/content'
    | '/departments'
    | '/notifications'
    | '/projects'
    | '/retainers'
    | '/tasks'
    | '/team'
    | '/templates'
    | '/approvals/requests/$requestId'
    | '/content/posts/$postId'
    | '/shoots/$shootId/edit'
    | '/shoots/$shootId'
  id:
    | '__root__'
    | '/_app'
    | '/activate'
    | '/login'
    | '/setup-two-factor'
    | '/_app/account'
    | '/_app/audit'
    | '/_app/design-system'
    | '/a/$token'
    | '/_app/'
    | '/_app/clients/$clientId'
    | '/_app/clients/new'
    | '/_app/departments/$departmentId'
    | '/_app/notifications/settings'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/_app/retainers/$retainerId'
    | '/_app/retainers/new'
    | '/_app/shoots/new'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/board'
    | '/_app/tasks/list'
    | '/_app/tasks/new'
    | '/_app/tasks/workload'
    | '/_app/team/$userId'
    | '/_app/team/new'
    | '/_app/templates/$templateId'
    | '/_app/templates/new'
    | '/_app/approvals/'
    | '/_app/calendar/'
    | '/_app/clients/'
    | '/_app/content/'
    | '/_app/departments/'
    | '/_app/notifications/'
    | '/_app/projects/'
    | '/_app/retainers/'
    | '/_app/tasks/'
    | '/_app/team/'
    | '/_app/templates/'
    | '/_app/approvals/requests/$requestId'
    | '/_app/content/posts/$postId'
    | '/_app/shoots/$shootId/edit'
    | '/_app/shoots/$shootId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  LoginRoute: typeof LoginRoute
  SetupTwoFactorRoute: typeof SetupTwoFactorRoute
  ATokenRoute: typeof ATokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-two-factor': {
      id: '/setup-two-factor'
      path: '/setup-two-factor'
      fullPath: '/setup-two-factor'
      preLoaderRoute: typeof SetupTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design-system': {
      id: '/_app/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/approvals/': {
      id: '/_app/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AppApprovalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/': {
      id: '/_app/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof AppContentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/': {
      id: '/_app/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$departmentId': {
      id: '/_app/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof AppDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/settings': {
      id: '/_app/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof AppNotificationsSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retainers/': {
      id: '/_app/retainers/'
      path: '/retainers'
      fullPath: '/retainers/'
      preLoaderRoute: typeof AppRetainersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retainers/$retainerId': {
      id: '/_app/retainers/$retainerId'
      path: '/retainers/$retainerId'
      fullPath: '/retainers/$retainerId'
      preLoaderRoute: typeof AppRetainersRetainerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retainers/new': {
      id: '/_app/retainers/new'
      path: '/retainers/new'
      fullPath: '/retainers/new'
      preLoaderRoute: typeof AppRetainersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shoots/new': {
      id: '/_app/shoots/new'
      path: '/shoots/new'
      fullPath: '/shoots/new'
      preLoaderRoute: typeof AppShootsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/board': {
      id: '/_app/tasks/board'
      path: '/tasks/board'
      fullPath: '/tasks/board'
      preLoaderRoute: typeof AppTasksBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/list': {
      id: '/_app/tasks/list'
      path: '/tasks/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AppTasksListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/new': {
      id: '/_app/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AppTasksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/workload': {
      id: '/_app/tasks/workload'
      path: '/tasks/workload'
      fullPath: '/tasks/workload'
      preLoaderRoute: typeof AppTasksWorkloadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/$userId': {
      id: '/_app/team/$userId'
      path: '/team/$userId'
      fullPath: '/team/$userId'
      preLoaderRoute: typeof AppTeamUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/new': {
      id: '/_app/team/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof AppTeamNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$templateId': {
      id: '/_app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals/requests/$requestId': {
      id: '/_app/approvals/requests/$requestId'
      path: '/approvals/requests/$requestId'
      fullPath: '/approvals/requests/$requestId'
      preLoaderRoute: typeof AppApprovalsRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/posts/$postId': {
      id: '/_app/content/posts/$postId'
      path: '/content/posts/$postId'
      fullPath: '/content/posts/$postId'
      preLoaderRoute: typeof AppContentPostsPostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shoots/$shootId/': {
      id: '/_app/shoots/$shootId/'
      path: '/shoots/$shootId'
      fullPath: '/shoots/$shootId/'
      preLoaderRoute: typeof AppShootsShootIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shoots/$shootId/edit': {
      id: '/_app/shoots/$shootId/edit'
      path: '/shoots/$shootId/edit'
      fullPath: '/shoots/$shootId/edit'
      preLoaderRoute: typeof AppShootsShootIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppDepartmentsDepartmentIdRoute: typeof AppDepartmentsDepartmentIdRoute
  AppNotificationsSettingsRoute: typeof AppNotificationsSettingsRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppRetainersRetainerIdRoute: typeof AppRetainersRetainerIdRoute
  AppRetainersNewRoute: typeof AppRetainersNewRoute
  AppShootsNewRoute: typeof AppShootsNewRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksBoardRoute: typeof AppTasksBoardRoute
  AppTasksListRoute: typeof AppTasksListRoute
  AppTasksNewRoute: typeof AppTasksNewRoute
  AppTasksWorkloadRoute: typeof AppTasksWorkloadRoute
  AppTeamUserIdRoute: typeof AppTeamUserIdRoute
  AppTeamNewRoute: typeof AppTeamNewRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppApprovalsIndexRoute: typeof AppApprovalsIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppContentIndexRoute: typeof AppContentIndexRoute
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppRetainersIndexRoute: typeof AppRetainersIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppApprovalsRequestsRequestIdRoute: typeof AppApprovalsRequestsRequestIdRoute
  AppContentPostsPostIdRoute: typeof AppContentPostsPostIdRoute
  AppShootsShootIdEditRoute: typeof AppShootsShootIdEditRoute
  AppShootsShootIdIndexRoute: typeof AppShootsShootIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAuditRoute: AppAuditRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppDepartmentsDepartmentIdRoute: AppDepartmentsDepartmentIdRoute,
  AppNotificationsSettingsRoute: AppNotificationsSettingsRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppRetainersRetainerIdRoute: AppRetainersRetainerIdRoute,
  AppRetainersNewRoute: AppRetainersNewRoute,
  AppShootsNewRoute: AppShootsNewRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksBoardRoute: AppTasksBoardRoute,
  AppTasksListRoute: AppTasksListRoute,
  AppTasksNewRoute: AppTasksNewRoute,
  AppTasksWorkloadRoute: AppTasksWorkloadRoute,
  AppTeamUserIdRoute: AppTeamUserIdRoute,
  AppTeamNewRoute: AppTeamNewRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppApprovalsIndexRoute: AppApprovalsIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppContentIndexRoute: AppContentIndexRoute,
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppRetainersIndexRoute: AppRetainersIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppApprovalsRequestsRequestIdRoute: AppApprovalsRequestsRequestIdRoute,
  AppContentPostsPostIdRoute: AppContentPostsPostIdRoute,
  AppShootsShootIdEditRoute: AppShootsShootIdEditRoute,
  AppShootsShootIdIndexRoute: AppShootsShootIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ActivateRoute: ActivateRoute,
  LoginRoute: LoginRoute,
  SetupTwoFactorRoute: SetupTwoFactorRoute,
  ATokenRoute: ATokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
