/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupTwoFactorRouteImport } from './routes/setup-two-factor'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppDesignSystemRouteImport } from './routes/_app/design-system'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients/new'
import { Route as AppDepartmentsIndexRouteImport } from './routes/_app/departments/index'
import { Route as AppDepartmentsDepartmentIdRouteImport } from './routes/_app/departments/$departmentId'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team/index'
import { Route as AppTeamUserIdRouteImport } from './routes/_app/team/$userId'
import { Route as AppTeamNewRouteImport } from './routes/_app/team/new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTwoFactorRoute = SetupTwoFactorRouteImport.update({
  id: '/setup-two-factor',
  path: '/setup-two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsIndexRoute = AppDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsDepartmentIdRoute =
  AppDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamUserIdRoute = AppTeamUserIdRouteImport.update({
  id: '/team/$userId',
  path: '/team/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamNewRoute = AppTeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/design-system': typeof AppDesignSystemRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/team/$userId': typeof AppTeamUserIdRoute
  '/team/new': typeof AppTeamNewRoute
  '/clients/': typeof AppClientsIndexRoute
  '/departments/': typeof AppDepartmentsIndexRoute
  '/team/': typeof AppTeamIndexRoute
}
export interface FileRoutesByTo {
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/design-system': typeof AppDesignSystemRoute
  '/': typeof AppIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/team/$userId': typeof AppTeamUserIdRoute
  '/team/new': typeof AppTeamNewRoute
  '/clients': typeof AppClientsIndexRoute
  '/departments': typeof AppDepartmentsIndexRoute
  '/team': typeof AppTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/design-system': typeof AppDesignSystemRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/_app/team/$userId': typeof AppTeamUserIdRoute
  '/_app/team/new': typeof AppTeamNewRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/departments/': typeof AppDepartmentsIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/login'
    | '/setup-two-factor'
    | '/account'
    | '/audit'
    | '/design-system'
    | '/clients/$clientId'
    | '/clients/new'
    | '/departments/$departmentId'
    | '/team/$userId'
    | '/team/new'
    | '/clients/'
    | '/departments/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activate'
    | '/login'
    | '/setup-two-factor'
    | '/account'
    | '/audit'
    | '/design-system'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/departments/$departmentId'
    | '/team/$userId'
    | '/team/new'
    | '/clients'
    | '/departments'
    | '/team'
  id:
    | '__root__'
    | '/_app'
    | '/activate'
    | '/login'
    | '/setup-two-factor'
    | '/_app/account'
    | '/_app/audit'
    | '/_app/design-system'
    | '/_app/'
    | '/_app/clients/$clientId'
    | '/_app/clients/new'
    | '/_app/departments/$departmentId'
    | '/_app/team/$userId'
    | '/_app/team/new'
    | '/_app/clients/'
    | '/_app/departments/'
    | '/_app/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  LoginRoute: typeof LoginRoute
  SetupTwoFactorRoute: typeof SetupTwoFactorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-two-factor': {
      id: '/setup-two-factor'
      path: '/setup-two-factor'
      fullPath: '/setup-two-factor'
      preLoaderRoute: typeof SetupTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design-system': {
      id: '/_app/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/': {
      id: '/_app/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$departmentId': {
      id: '/_app/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof AppDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/$userId': {
      id: '/_app/team/$userId'
      path: '/team/$userId'
      fullPath: '/team/$userId'
      preLoaderRoute: typeof AppTeamUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/new': {
      id: '/_app/team/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof AppTeamNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppDepartmentsDepartmentIdRoute: typeof AppDepartmentsDepartmentIdRoute
  AppTeamUserIdRoute: typeof AppTeamUserIdRoute
  AppTeamNewRoute: typeof AppTeamNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAuditRoute: AppAuditRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppDepartmentsDepartmentIdRoute: AppDepartmentsDepartmentIdRoute,
  AppTeamUserIdRoute: AppTeamUserIdRoute,
  AppTeamNewRoute: AppTeamNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ActivateRoute: ActivateRoute,
  LoginRoute: LoginRoute,
  SetupTwoFactorRoute: SetupTwoFactorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
