import { z } from 'zod';
import { instantSchema } from './dates.js';
import { pageQuerySchema, pageSchema } from './lists.js';

/** Every audited change, as `<entity>.<verb>`. Features add theirs with their spec. */
export const AUDIT_ACTIONS = [
  'user.created',
  'user.updated',
  'user.roles_changed',
  'user.departments_changed',
  'user.archived',
  'user.restored',
  'user.link_issued',
  'user.password_set',
  'user.password_changed',
  'user.two_factor_enabled',
  'user.two_factor_disabled',
  'user.two_factor_reset',
  'user.backup_codes_regenerated',
  'user.profile_updated',
  'department.updated',
  'client.created',
  'client.updated',
  'client.status_changed',
  'client.account_manager_changed',
  'client.healthcare_changed',
  'client.archived',
  'client.restored',
  'client.brand_kit_updated',
  'client.emailed',
  'client_contact.created',
  'client_contact.updated',
  'client_contact.archived',
  'client_platform_account.created',
  'client_platform_account.updated',
  'client_platform_account.archived',
  'client_note.created',
  'client_note.updated',
  'client_note.archived',
  'project.created',
  'project.updated',
  'project.project_manager_changed',
  'project.status_changed',
  'project.money_updated',
  'project.archived',
  'project.restored',
  'project_milestone.created',
  'project_milestone.updated',
  'project_milestone.reordered',
  'project_milestone.completed',
  'project_milestone.reopened',
  'project_milestone.archived',
  'retainer.created',
  'retainer.updated',
  'retainer.status_changed',
  'retainer.deliverables_updated',
  'retainer.money_updated',
  'retainer.archived',
  'retainer.restored',
  'retainer_cycle.created',
  'retainer_cycle.closed',
  'retainer_cycle.line_updated',
  'retainer_cycle.line_added',
  'retainer_cycle.adjusted',
  'retainer_charge.created',
  'retainer_charge.amount_changed',
  'retainer_charge.cancelled',
  'retainer_charge.split',
  'retainer_charge.settled_outside',
  'retainer_term.created',
  'retainer_term.updated',
  'retainer_term.end_action_changed',
  'retainer_term.cancelled',
  'retainer_term.started',
  'retainer_term.completed',
  'retainer_term.renewed',
  'retainer_amendment.created',
  'retainer_amendment.approved',
  'retainer_amendment.rejected',
  'retainer_amendment.withdrawn',
  'retainer_amendment.applied',
  'retainer_amendment.cancelled',
  'extra_work.created',
  'extra_work.updated',
  'extra_work.billing_changed',
  'extra_work.archived',
  'task.created',
  'task.updated',
  'task.assigned',
  'task.department_changed',
  'task.status_changed',
  'task.dependencies_updated',
  'task.archived',
  'task.restored',
  'task.revision_decided',
  'task.request_scope_changed',
  'task.extra_work_moved',
  'task.reviewed',
  'task.client_text_updated',
  'task.client_response_recorded',
  'task_checklist_item.created',
  'task_checklist_item.updated',
  'task_checklist_item.reordered',
  'task_checklist_item.archived',
  'task_link.created',
  'task_link.archived',
  'task_comment.created',
  'task_comment.updated',
  'task_comment.archived',
  'template.created',
  'template.updated',
  'template.assignees_updated',
  'template.archived',
  'template.restored',
  'template_run.created',
  'retainer.template_changed',
  'file_item.created',
  'file_item.renamed',
  'file_item.confidential_changed',
  'file_item.archived',
  'file_item.restored',
  'file_version.created',
  'file_version.archived',
  'file_version.restored',
  'file_version.final_set',
  'file_version.final_cleared',
  'approval_request.created',
  'approval_request.link_reissued',
  'approval_request.revoked',
  'approval_request.emailed',
  'approval_item.responded',
  'approval_item.withdrawn',
  'post.created',
  'post.updated',
  'post.status_changed',
  'post.reviewed',
  'post.client_response_recorded',
  'post.task_linked',
  'post.task_unlinked',
  'post.task_returned',
  'post.duplicated',
  'post.archived',
  'post.restored',
  'shoot.created',
  'shoot.updated',
  'shoot.shots_changed',
  'shoot.shot_ticked',
  'shoot.shot_unticked',
  'shoot.completed',
  'shoot.cancelled',
  'shoot.reopened',
  'shoot.archived',
  'shoot.restored',
  'meeting.created',
  'meeting.updated',
  'meeting.cancelled',
  'meeting.archived',
  'meeting.restored',
  'catalog_service.created',
  'catalog_service.updated',
  'catalog_service.archived',
  'catalog_service.restored',
  'catalog_package.created',
  'catalog_package.updated',
  'catalog_package.archived',
  'catalog_package.restored',
  'quote_settings.updated',
  'quote.created',
  'quote.updated',
  'quote.approval_requested',
  'quote.approval_withdrawn',
  'quote.approval_approved',
  'quote.approval_returned',
  'quote.sent',
  'quote.extended',
  'quote.expired',
  'quote.rejected',
  'quote.accepted',
  'quote.version_created',
  'quote.superseded',
  'quote.archived',
  'quote.emailed',
  'invoice_settings.updated',
  'invoice.created',
  'invoice.updated',
  'invoice.archived',
  'invoice.issued',
  'invoice.due_date_changed',
  'invoice.voided',
  'invoice.overdue',
  'invoice.services_changed',
  'invoice.emailed',
  'payment.recorded',
  'payment.voided',
  'payment.emailed',
  'project_expense.created',
  'project_expense.updated',
  'project_expense.archived',
  'ad_campaign.created',
  'ad_campaign.updated',
  'ad_campaign.status_changed',
  'ad_campaign.archived',
  'ad_campaign.restored',
  'ad_campaign_update.created',
  'ad_campaign_update.updated',
  'ad_campaign_update.archived',
  'ad_wallet.threshold_changed',
  'ad_wallet.low_balance',
  'ad_wallet.low_balance_cleared',
  'ad_wallet_entry.recorded',
  'ad_wallet_entry.voided',
  'ad_wallet_entry.emailed',
  'lead.created',
  'lead.updated',
  'lead.stage_changed',
  'lead.owner_changed',
  'lead.follow_up_changed',
  'lead.lost',
  'lead.reopened',
  'lead.converted',
  'lead.archived',
  'lead.restored',
  'lead_note.created',
  'lead_note.updated',
  'lead_note.archived',
  'client_report.summary_changed',
] as const;

export const auditActionSchema = z.enum(AUDIT_ACTIONS).meta({ id: 'AuditAction' });

export type AuditAction = z.infer<typeof auditActionSchema>;

export const AUDIT_ENTITY_TYPES = [
  'user',
  'department',
  'client',
  'client_contact',
  'client_platform_account',
  'client_note',
  'project',
  'project_milestone',
  'retainer',
  'retainer_cycle',
  'retainer_charge',
  'retainer_term',
  'retainer_amendment',
  'extra_work',
  'task',
  'task_checklist_item',
  'task_link',
  'task_comment',
  'template',
  'template_run',
  'file_item',
  'approval_request',
  'post',
  'shoot',
  'meeting',
  'catalog_service',
  'catalog_package',
  'quote_settings',
  'quote',
  'invoice_settings',
  'invoice',
  'payment',
  'project_expense',
  'ad_campaign',
  'ad_campaign_update',
  'ad_wallet',
  'ad_wallet_entry',
  'lead',
  'lead_note',
  'client_report',
] as const;

export const auditEntityTypeSchema = z.enum(AUDIT_ENTITY_TYPES).meta({ id: 'AuditEntityType' });

export type AuditEntityType = z.infer<typeof auditEntityTypeSchema>;

/** The changed fields of a record, before or after a change. */
const changedFieldsSchema = z.record(z.string(), z.unknown()).nullable();

export const auditEntrySchema = z
  .object({
    id: z.uuid(),
    occurredAt: z.iso.datetime(),
    actorId: z.uuid().nullable(),
    actorName: z.string().nullable(),
    action: auditActionSchema,
    entityType: auditEntityTypeSchema,
    entityId: z.uuid(),
    before: changedFieldsSchema,
    after: changedFieldsSchema,
  })
  .meta({ id: 'AuditEntry', description: 'One audited change; a null actor is the system' });

export type AuditEntry = z.infer<typeof auditEntrySchema>;

export const auditListQuerySchema = pageQuerySchema.extend({
  entityType: auditEntityTypeSchema.optional(),
  entityId: z.uuid().optional(),
  actorId: z.uuid().optional(),
  action: auditActionSchema.optional(),
  from: instantSchema.optional(),
  to: instantSchema.optional(),
});

export type AuditListQuery = z.infer<typeof auditListQuerySchema>;

export const auditPageSchema = pageSchema(auditEntrySchema).meta({
  id: 'AuditPage',
  description: 'Audit entries, newest first',
});

export type AuditPage = z.infer<typeof auditPageSchema>;
