import { z } from 'zod';

/**
 * Codes the API puts on errors the UI must tell apart (ADR 0013). The web app shows the
 * translation of `errors.<code>`; the server message is English and never shown.
 */
export const ERROR_CODES = [
  'TWO_FACTOR_REQUIRED',
  'EMAIL_TAKEN',
  'GENERAL_MANAGER_ONLY',
  'LAST_GENERAL_MANAGER',
  'CANNOT_ARCHIVE_SELF',
  'CANNOT_CHANGE_OWN_ROLES',
  'USER_HAS_RESPONSIBILITIES',
  'USER_ARCHIVED',
  'USER_NOT_ARCHIVED',
  'PRIMARY_DEPARTMENT_REQUIRED',
  'UNKNOWN_DEPARTMENT',
  'MANAGER_NOT_MEMBER',
  'MANAGER_MEMBERSHIP_REQUIRED',
  'DEPARTMENT_NAME_TAKEN',
  'LINK_INVALID',
  'CLIENT_NAME_TAKEN',
  'INVALID_ACCOUNT_MANAGER',
  'CLIENT_ARCHIVED',
  'CLIENT_NOT_ARCHIVED',
  'LIMIT_REACHED',
  'UNKNOWN_CONTACT',
  'NOT_NOTE_AUTHOR',
  'NOTE_ARCHIVED',
  'CLIENT_ENDED',
  'INVALID_PROJECT_MANAGER',
  'INVALID_DATES',
  'PROJECT_NAME_TAKEN',
  'PROJECT_CLOSED',
  'PROJECT_ARCHIVED',
  'PROJECT_NOT_ARCHIVED',
  'CURRENCY_LOCKED',
  'INVALID_TRANSITION',
  'MILESTONES_OPEN',
  'INVALID_ORDER',
  'MILESTONE_DONE',
  'MILESTONE_NOT_DONE',
  'MILESTONE_HAS_OPEN_TASKS',
  'RETAINER_NAME_TAKEN',
  'RETAINER_ENDED',
  'RETAINER_ARCHIVED',
  'RETAINER_NOT_ARCHIVED',
  'RETAINER_STARTED',
  'DUPLICATE_DELIVERABLE',
  'CYCLE_CLOSED',
  'NEGATIVE_DELIVERED',
  'BILLING_NOTE_REQUIRED',
  'ASSIGNEE_REQUIRED',
  'INVALID_ASSIGNEE',
  'TASK_BLOCKED',
  'INVALID_DEPENDENCY',
  'DEPENDENCY_CYCLE',
  'INVALID_LINK',
  'NO_ENGAGEMENT',
  'EXTRA_WORK_BILLED',
  'NOT_OVER_LIMIT',
  'ALREADY_DECIDED',
  'INVALID_MENTION',
  'NOT_COMMENT_AUTHOR',
  'TASK_ARCHIVED',
  'TASK_NOT_ARCHIVED',
  'TASKS_OPEN',
  'TEMPLATE_NAME_TAKEN',
  'TEMPLATE_ARCHIVED',
  'TEMPLATE_NOT_ARCHIVED',
  'TEMPLATE_KIND_MISMATCH',
  'TEMPLATE_NOT_LINKED',
  'NO_TEMPLATE',
  'NO_REPEATED_STEP',
  'NOTHING_MISSING',
  'ALREADY_GENERATED',
  'NOT_MUTABLE',
  'CONCURRENT_CHANGE',
  'FILE_EMPTY',
  'FILE_TOO_LARGE',
  'FILE_TYPE_BLOCKED',
  'STORAGE_FULL',
  'UPLOAD_NOT_FOUND',
  'LINK_NOT_ALLOWED',
  'NOT_VERSIONED',
  'NOT_DELIVERABLE',
  'FILE_NAME_TAKEN',
  'VERSION_FINAL',
  'LAST_VERSION',
  'TASK_CLOSED',
  'TASK_NOT_APPROVED',
  'NOT_CONFIDENTIAL_READER',
  'REVIEW_CONTENT_CHANGED',
  'NOTHING_TO_APPROVE',
  'SELF_REVIEW',
  'MEDICAL_REVIEW_REQUIRED',
  'TASK_NOT_READY',
  'CONTACT_NOT_APPROVER',
  'REQUEST_CLOSED',
  'SENT_TO_CLIENT',
  'ITEM_ALREADY_DECIDED',
  'ITEM_WITHDRAWN',
  'APPROVAL_LINK_INVALID',
  'APPROVAL_LINK_EXPIRED',
  'VERSION_SENT',
  'POST_LOCKED',
  'POST_ARCHIVED',
  'INVALID_RESPONSIBLE',
  'PUBLISH_TIME_REQUIRED',
  'POST_NOT_READY',
  'POST_TASKS_NOT_READY',
  'POST_COUNTED_BY_TASK',
  'LINKED_TO_POST',
  'TASK_ALREADY_LINKED',
  'TASK_NOT_LINKABLE',
  'ALREADY_RETURNED',
  'TASK_NOT_BOOKABLE',
  'TASK_HAS_SHOOT',
  'LEAD_REQUIRED',
  'INVALID_CREW',
  'INVALID_ATTENDEE',
  'SCHEDULE_CONFLICT',
  'SHOOT_NOT_SCHEDULED',
  'SHOOT_NOT_STARTED',
  'SHOOT_NOT_CANCELLED',
  'SHOOT_ARCHIVED',
  'SHOOT_NOT_ARCHIVED',
  'MEETING_NOT_SCHEDULED',
  'MEETING_ARCHIVED',
  'MEETING_NOT_ARCHIVED',
  'SERVICE_NAME_TAKEN',
  'SERVICE_ARCHIVED',
  'SERVICE_NOT_ARCHIVED',
  'SERVICE_IN_USE',
  'SERVICE_IN_PACKAGE',
  'PACKAGE_NAME_TAKEN',
  'PACKAGE_ARCHIVED',
  'PACKAGE_NOT_ARCHIVED',
  'INVALID_PACKAGE_ITEM',
  'INVALID_TEMPLATE',
  'QUOTE_LOCKED',
  'APPROVAL_PENDING',
  'STALE_QUOTE',
  'CATALOG_ITEM_ARCHIVED',
  'INVALID_DISCOUNT',
  'INVALID_INSTALLMENTS',
  'APPROVAL_NOT_NEEDED',
  'QUOTE_EMPTY',
  'ZERO_PRICE',
  'DISCOUNT_APPROVAL_REQUIRED',
  'VERSION_EXISTS',
  'NOTE_REQUIRED',
  'CURRENCY_MISMATCH',
  'QUOTE_EXPIRED',
  'INVOICE_LOCKED',
  'STALE_INVOICE',
  'MIXED_ENGAGEMENTS',
  'ALREADY_INVOICED',
  'INVOICE_EMPTY',
  'RATE_REQUIRED',
  'INVOICE_HAS_PAYMENTS',
  'MILESTONE_INVOICED',
  'BILLED_BY_INVOICE',
  'OVERPAYMENT',
  'INVALID_OWNER',
  'INVALID_ENGAGEMENT',
  'FUNDING_LOCKED',
  'CAMPAIGN_HAS_UPDATES',
  'PERIOD_CROSSES_MONTH',
  'PERIOD_OVERLAP',
  'REFUND_EXCEEDS_BALANCE',
  'CONTACT_REQUIRED',
  'INVALID_LEAD_OWNER',
  'STALE_LEAD',
  'LEAD_CLOSED',
  'LEAD_ARCHIVED',
  'LEAD_HAS_SENT_QUOTE',
  'LEAD_HAS_QUOTES',
] as const;

export const errorCodeSchema = z.enum(ERROR_CODES).meta({ id: 'ErrorCode' });

export type ErrorCode = z.infer<typeof errorCodeSchema>;

/**
 * The body of every error response (ADR 0013). The API's own errors carry `statusCode`;
 * Better Auth's (under /api/auth) carry `code` and `message` only.
 */
export const errorResponseSchema = z
  .object({
    statusCode: z.number().int().optional(),
    code: z.string().optional(),
    message: z.string(),
    /**
     * Extra data for some codes: `responsibilitySchema[]` for `USER_HAS_RESPONSIBILITIES`,
     * `scheduleConflictSchema[]` for `SCHEDULE_CONFLICT`.
     */
    details: z.unknown().optional(),
  })
  .meta({ id: 'ErrorResponse', description: 'An error; `code` tells errors apart' });

export type ErrorResponse = z.infer<typeof errorResponseSchema>;

/**
 * Something a user is responsible for, which blocks archiving them (F01 rule 9, F05 rule 4, F06, F08 rule 28, F11, F03) or
 * removing their Account Manager role (F02 rule 8).
 */
export const responsibilitySchema = z
  .object({
    type: z.enum([
      'manages_department',
      'account_manager_of_client',
      'project_manager_of_project',
      'assignee_of_open_tasks',
      'responsible_for_open_posts',
      'lead_of_scheduled_shoots',
      'organizer_of_upcoming_meetings',
      'owner_of_open_leads',
    ]),
    id: z.uuid(),
    name: z.string(),
  })
  .meta({ id: 'Responsibility' });

export type Responsibility = z.infer<typeof responsibilitySchema>;
