#!/usr/bin/env bash
# Server setup for hub.vertexmedia.pro (docs/deployment.md). Idempotent: safe to run again, it
# only creates what is missing and reinstalls the configuration files from the repository.
# Run as root from a checkout, streaming this file:
#
#   ssh vertex 'bash -s' < deploy/provision.sh            # configuration from origin/main
#   ssh vertex 'bash -s -- <ref>' < deploy/provision.sh   # from another ref
#
# It never prints secrets. The database password and the auth secret are generated here and
# written only to /srv/hub.vertexmedia.pro/shared/.env (600).
set -euo pipefail

DOMAIN=hub.vertexmedia.pro
APP_USER=vertexhub
SITE_DIR=/srv/$DOMAIN
LOG_DIR=/var/log/$DOMAIN
BACKUP_DIR=/var/backups/$DOMAIN
ACME_ROOT=/var/www/vertexhub-acme
REPO_URL=https://github.com/HussienALfajer/vertex-hub.git
DB=vertex_hub
API_PORT=3050
SERVER_IP=109.199.111.169
REF=${1:-origin/main}

step() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
# The whole body is one function, so bash has read all of it before anything runs: commands
# that read stdin cannot swallow the rest of a script streamed through `ssh ... bash -s`.
main() {
[ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }

step "Preflight"
if ss -ltn | awk 'NR>1{print $4}' | grep -qx "127.0.0.1:$API_PORT"; then
  pgrep -u "$APP_USER" >/dev/null 2>&1 || { echo "port $API_PORT is taken by another program" >&2; exit 1; }
fi
resolved=$(getent ahostsv4 "$DOMAIN" | awk 'NR==1{print $1}' || true)
[ "$resolved" = "$SERVER_IP" ] || { echo "$DOMAIN resolves to '${resolved:-nothing}', expected $SERVER_IP" >&2; exit 1; }
echo "DNS ok, port $API_PORT free"

step "System user $APP_USER"
if ! id "$APP_USER" >/dev/null 2>&1; then
  useradd --system --user-group --create-home --home-dir "/home/$APP_USER" --shell /bin/bash "$APP_USER"
  echo "created"
fi
chmod 750 "/home/$APP_USER"

step "Directories"
install -d -o "$APP_USER" -g "$APP_USER" -m 755 "$SITE_DIR" "$SITE_DIR/releases" "$SITE_DIR/fonts" "$SITE_DIR/fonts/madani"
# nginx (group www-data) may only pass through shared/ to reach the files it serves for
# X-Accel-Redirect (F10, ADR 0019); .env stays 600, and files/ is setgid so new folders keep
# the group.
install -d -o "$APP_USER" -g www-data -m 710 "$SITE_DIR/shared"
install -d -o "$APP_USER" -g www-data -m 2750 "$SITE_DIR/shared/files"
install -d -o "$APP_USER" -g "$APP_USER" -m 750 "$LOG_DIR"
install -d -o root -g root -m 700 "$BACKUP_DIR"
install -d -o root -g root -m 755 "$ACME_ROOT"

step "Repository"
if [ ! -d "$SITE_DIR/repo.git" ]; then
  runuser -u "$APP_USER" -- git init --quiet --bare "$SITE_DIR/repo.git"
  runuser -u "$APP_USER" -- git -C "$SITE_DIR/repo.git" remote add origin "$REPO_URL"
fi
runuser -u "$APP_USER" -- git -C "$SITE_DIR/repo.git" fetch --quiet --prune origin \
  '+refs/heads/*:refs/remotes/origin/*'
sha=$(runuser -u "$APP_USER" -- git -C "$SITE_DIR/repo.git" rev-parse --verify "$REF^{commit}")
src=$(mktemp -d)
trap 'rm -rf "$src"' EXIT
runuser -u "$APP_USER" -- git -C "$SITE_DIR/repo.git" archive "$sha" deploy | tar -x -C "$src"
echo "configuration from ${sha:0:7}"

step "Scripts, systemd units, logrotate"
install -m 755 "$src/deploy/bin/vertexhub-deploy" /usr/local/bin/vertexhub-deploy
install -m 755 "$src/deploy/bin/vertexhub-healthcheck" /usr/local/bin/vertexhub-healthcheck
install -m 700 "$src/deploy/bin/vertexhub-backup" /usr/local/sbin/vertexhub-backup
for unit in pm2-vertexhub.service vertexhub-health.service vertexhub-health.timer \
  vertexhub-backup.service vertexhub-backup.timer; do
  install -m 644 "$src/deploy/systemd/$unit" "/etc/systemd/system/$unit"
done
install -m 644 "$src/deploy/logrotate/$DOMAIN" "/etc/logrotate.d/$DOMAIN"
systemctl daemon-reload

step "PostgreSQL"
env_file="$SITE_DIR/shared/.env"
role_exists=$(runuser -u postgres -- psql -tAc "select 1 from pg_roles where rolname = '$DB'")
if [ "$role_exists" != 1 ]; then
  [ ! -e "$env_file" ] || { echo "$env_file exists but role $DB does not; refusing to guess" >&2; exit 1; }
  db_password=$(openssl rand -hex 32)
  # Through stdin, not argv: other users on the server can read process arguments.
  runuser -u postgres -- psql -q -v ON_ERROR_STOP=1 <<SQL
create role $DB login password '$db_password';
create database $DB owner $DB encoding 'UTF8' template template0;
revoke all on database $DB from public;
SQL
  (
    umask 077
    cat >"$env_file" <<EOF
# Production environment for hub.vertexmedia.pro (generated by deploy/provision.sh).
NODE_ENV=production
LOG_LEVEL=info
API_HOST=127.0.0.1
API_PORT=$API_PORT
APP_URL=https://$DOMAIN
BETTER_AUTH_SECRET=$(openssl rand -hex 32)
DATABASE_URL=postgres://$DB:$db_password@127.0.0.1:5432/$DB
WORKER_NAME=production
FILES_ROOT=$SITE_DIR/shared/files
EOF
  )
  chown "$APP_USER:$APP_USER" "$env_file"
  unset db_password
  echo "role, database and $env_file created"
else
  [ -f "$env_file" ] || { echo "role $DB exists but $env_file is missing" >&2; exit 1; }
  echo "already set up"
fi
# Files (F10) arrived after the first provisioning: add their root to an existing .env once.
grep -q '^FILES_ROOT=' "$env_file" || echo "FILES_ROOT=$SITE_DIR/shared/files" >>"$env_file"
chmod 600 "$env_file"

step "nginx"
# The site relies on the server's shared security headers and the general request zones, which
# this folder does not install: refuse to go on without them, rather than serve without HSTS.
grep -q 'Strict-Transport-Security' /etc/nginx/snippets/security-headers.conf 2>/dev/null ||
  { echo "/etc/nginx/snippets/security-headers.conf with HSTS is missing" >&2; exit 1; }
for zone in 'zone=general:' 'zone=perip:'; do
  nginx -T 2>/dev/null | grep -q "$zone" ||
    { echo "the nginx ${zone%:} zone the site uses is not defined" >&2; exit 1; }
done
install -m 644 "$src/deploy/nginx/vertexhub-csp.conf" /etc/nginx/snippets/vertexhub-csp.conf
install -m 644 "$src/deploy/nginx/vertexhub-headers.conf" /etc/nginx/snippets/vertexhub-headers.conf
install -m 644 "$src/deploy/nginx/vertexhub-proxy.conf" /etc/nginx/snippets/vertexhub-proxy.conf
install -m 644 "$src/deploy/nginx/vertexhub-limits.conf" /etc/nginx/conf.d/vertexhub-limits.conf

available=/etc/nginx/sites-available/$DOMAIN
enabled=/etc/nginx/sites-enabled/$DOMAIN
cert=/etc/letsencrypt/live/$DOMAIN/fullchain.pem

# A config that fails `nginx -t` is removed from sites-enabled at once: one broken file there
# takes every site down on the next reload or restart (SERVER.md rule 1).
activate() {
  install -m 644 "$1" "$available"
  ln -sfn "$available" "$enabled"
  if ! nginx -t 2>/tmp/vertexhub-nginx-test; then
    rm -f "$enabled"
    cat /tmp/vertexhub-nginx-test >&2
    echo "nginx rejected the configuration; the site was disabled again, other sites untouched" >&2
    exit 1
  fi
  systemctl reload nginx
}

if [ ! -f "$cert" ]; then
  activate "$src/deploy/nginx/$DOMAIN.bootstrap"
  certbot certonly --webroot -w "$ACME_ROOT" -d "$DOMAIN" --non-interactive --keep-until-expiring
fi
activate "$src/deploy/nginx/$DOMAIN"
echo "site enabled with TLS"

step "fail2ban"
# The nginx jails expand their log globs when they start: reload them to watch the new logs.
for jail in nginx-4xx-flood nginx-limit-req; do
  if fail2ban-client status "$jail" >/dev/null 2>&1; then
    fail2ban-client reload "$jail" >/dev/null && echo "$jail reloaded"
  fi
done

step "PM2 service"
systemctl enable --now pm2-vertexhub.service
systemctl is-active pm2-vertexhub.service

step "Backup timer"
systemctl enable --now vertexhub-backup.timer

step "Chromium libraries"
# The worker renders quote PDFs with Playwright's Chromium (F04, ADR 0008). The browser itself
# is downloaded by each deploy as $APP_USER; its system libraries need root, and Playwright
# knows the list for this Ubuntu release, so they come from the current release.
if [ -d "$SITE_DIR/current" ]; then
  (cd "$SITE_DIR/current" && corepack pnpm --filter @vertex-hub/worker exec playwright install-deps chromium)
  echo "installed"
else
  echo "no release yet: re-run provision.sh after the first deploy"
fi

cat <<EOF

Provisioning complete. Next:
  vertexhub-deploy                                   # first release
  systemctl enable --now vertexhub-health.timer      # once the first release is healthy
EOF
}

main "$@"
